# -*- coding: utf-8 -*-
"""final_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AOeMGqngeXbVl2KuTHTJbg9WZUH2Ev0N
"""

class employee():
  def __init__(self,name,age):
    self.name = name
    self.age = age
    self.language = set()
  def emp_detail(self):
    print("Name is",self.name,"and age is",self.age)
  def addLanguage(self,*new_lang):
    self.language.update(new_lang)
    print("Laguages updated")
  def language_info(self):
    print(self.name,"speaks:",*self.language)



class manager(employee):
  def __init__(self,name,age,status):
    super().__init__(name,age)
    self.status = status
  
  def manager_info(self):
    print(self.name,"is a",self.status,"with age",self.age)

# First value of database
ob1 = employee('Rat',25)
ob1.emp_detail()

ob1.addLanguage("Spanish","Korean","Hindi")

ob1.language_info()

#Second value of database
ob2 = manager("Rohan",35,"Manager")

ob2.manager_info()

ob2.addLanguage("Malyalam","Tamil","English")
ob2.language_info()

#Third value od database
ob3 = manager("Ram",40,"Manager")

ob3.addLanguage("Russian","French","English")

ob3.language_info()

# Database of Company Management system
my_dict = { "Rat": {"Employee":ob1}, "Rohan": {"Manager":ob2},"Ram": {"Manager":ob3}}

emp_language = input("Enter the name of employee to get what language he speaks:")
emp_dict = my_dict[emp_language]
if list(emp_dict.keys())[0] == "Manager":
  emp_dict["Manager"].language_info()
else:
  emp_dict["Employee"].language_info()