# -*- coding: utf-8 -*-
"""Day 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ezvfx8Km0IrJmNf3jYk4dsBXxuNYVJvE

# Question 1
"""

list_item = ["onion","potato","brinjal","cabbage","palak","corriender"]
temp = ''
for i in range(len(list_item)//2):
  temp = list_item[i]
  list_item[i] = list_item[len(list_item)//2 +i]
  list_item[len(list_item)//2 +i] = temp
print(list_item)

"""# Question 2"""

n = int(input())
print([x for x in range(n+1) if x%2 == 0])