# -*- coding: utf-8 -*-
"""day_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RcY3db-Kl9ziVHXoL2A5QOn8g4hcVrns
"""

class animal():
  def __init__(self,animalType,legs):
    self.type = animalType
    self.legs = legs
  def info(self):
   print("The",self.type,"has",self.legs,"legs")

class dogs(animal):
  def __init__(self,animalType,legs,color):
    super().__init__(animalType,legs)
    self.color = color
  def dog_color(self):
    print("My",self.type,"is of",self.color,"color")
class cats(animal):
  def __init__(self,animalType,legs,breed):
    super().__init__(animalType,legs)
    self.breed = breed
  def cat_breed(self):
    print("My",self.type,"is of",self.breed,"breed")

ob1 = dogs("dog",4,"back")
ob1.dog_color()

ob2 = cats("cat",4,"persian")
ob2.cat_breed()