# -*- coding: utf-8 -*-
"""day_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ot_-j3hVF9E_l5XwKL9HZ0yqO3OQeO7h

# Question 1
"""

username = 'ratnadeep'
password = 'india'
ip_username = input("Username: ")
ip_password = input("Password: ")
if username == ip_username and password != ip_password:
  print("Invalid Password")
elif username != ip_username and password == ip_password:
  print("Invalid Username")
elif username != ip_username and password != ip_password:
  print("Invalid password and username")
else:
  print("Successfully Login")

"""# Question 2"""

user_pass = {"ratnadeep":"india","athar": "pakistan","rashford":"england","ronaldo":"brazil"}
ip_username = input("Username: ")
ip_password = input("Password: ")
if ip_username not in user_pass and user_pass.get(ip_username) != ip_password:
  print("Invalid password and username")
elif user_pass.get(ip_username) != ip_password:
  print("Invalid password")
else:
  print("Successfully Login")