# -*- coding: utf-8 -*-
"""day_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tKwtXJ2D2ByCTHieBui604hpYBOigAE3

# Question 1
"""

import math
def prime_number(start,end):
  prime = []
  if start == 0:
    start +=2
  elif start == 1:
    start +=1
  for i in range(start,end):
    for j in range(2,int(math.sqrt(i))+1):
      if i % j ==0:
        break
    else:
      prime.append(i)
  return prime
prime = prime_number(0,100)
print(prime)